export const REALTIME_CONSTANTS = {
  HEARTBEAT_INTERVAL_MS: 15_000,
  HEARTBEAT_TIMEOUT_MS: 45_000,
  MAX_PAYLOAD_BYTES: 16 * 1024, // 16 KB
  MAX_REQUEST_ID_LENGTH: 64,
  REQUEST_ID_REGEX: /^[a-zA-Z0-9_.:-]+$/,
  RATE_LIMIT_WINDOW_MS: 10_000,
  RATE_LIMIT_MAX_EVENTS: 50,
  RATE_LIMIT_MAX_MALFORMED: 5,
} as const;
