import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const STARTER_COMPANIONS = [
  {
    slug: 'bando-panda',
    nameAr: 'باندو',
    nameEn: 'Bando',
    descriptionAr: 'الباندا الحكيم الهادئ، محب للمشروبات المنعشة والمجالس الهادئة.',
    archetype: 'panda',
    placeholderAsset: 'mascot_bando.png',
    isStarter: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: 'luna-bunny',
    nameAr: 'لونا',
    nameEn: 'Luna',
    descriptionAr: 'أرنوبة نشيطة سريعة البديهة تعشق المغامرات والتحديات الجماعية.',
    archetype: 'bunny',
    placeholderAsset: 'mascot_luna.png',
    isStarter: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: 'misho-cat',
    nameAr: 'ميشو',
    nameEn: 'Misho',
    descriptionAr: 'قط فضولي ذكي ولعوب، يراقب كل خطوة في اللعبة بحماس.',
    archetype: 'cat',
    placeholderAsset: 'mascot_misho.png',
    isStarter: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: 'zaatar-fox',
    nameAr: 'زعتر',
    nameEn: 'Zaatar',
    descriptionAr: 'ثعلب ذكي ومكار ولطيف، خبير في استراتيجيات ألعاب الورق والخداع.',
    archetype: 'fox',
    placeholderAsset: 'mascot_zaatar.png',
    isStarter: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: 'kiki-koala',
    nameAr: 'كيكي',
    nameEn: 'Kiki',
    descriptionAr: 'كوالا محبوب هادئ الطباع يحب الاسترخاء والمشروبات الساخنة.',
    archetype: 'koala',
    placeholderAsset: 'mascot_kiki.png',
    isStarter: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: 'fando-penguin',
    nameAr: 'فندو',
    nameEn: 'Fando',
    descriptionAr: 'بطريق شهم مرح متزلج، ينشر البهجة والضحك أينما حل.',
    archetype: 'penguin',
    placeholderAsset: 'mascot_fando.png',
    isStarter: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: 'rocco-raccoon',
    nameAr: 'روكو',
    nameEn: 'Rocco',
    descriptionAr: 'راكون مستكشف ذو حيلة وبراعة في حل الألغاز واقتناص الفرص.',
    archetype: 'raccoon',
    placeholderAsset: 'mascot_rocco.png',
    isStarter: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: 'dino-rexy',
    nameAr: 'ركسي',
    nameEn: 'Rexy',
    descriptionAr: 'ديناصور صغير لطيف وشجاع، قلبه كبير ويحب تشجيع أصدقائه.',
    archetype: 'tiny_dino',
    placeholderAsset: 'mascot_rexy.png',
    isStarter: true,
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: 'simba-lion',
    nameAr: 'سيمو',
    nameEn: 'Simo',
    descriptionAr: 'شبل مرح وقائد بالفطرة يحب التنافس الحماسي الشريف.',
    archetype: 'lion_cub',
    placeholderAsset: 'mascot_simo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: 'nimo-otter',
    nameAr: 'نيمو',
    nameEn: 'Nimo',
    descriptionAr: 'قضاعة مائية مرحة وسريعة، محبة للمنافسات السريعة والمرح.',
    archetype: 'otter',
    placeholderAsset: 'mascot_nimo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: 'zizo-monkey',
    nameAr: 'زيزو',
    nameEn: 'Zizo',
    descriptionAr: 'قرد بارع في الحيل والقفز، لا يمل من المزاح وإشعال أجواء التحدي.',
    archetype: 'monkey',
    placeholderAsset: 'mascot_zizo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: 'tut-bird',
    nameAr: 'توت',
    nameEn: 'Tut',
    descriptionAr: 'طائر مغرد متفائل يجلب الحظ السعيد والأخبار الطيبة دائماً.',
    archetype: 'bird',
    placeholderAsset: 'mascot_tut.png',
    isStarter: true,
    isActive: true,
    sortOrder: 12,
  },
  {
    slug: 'barood-bear',
    nameAr: 'بارود',
    nameEn: 'Barood',
    descriptionAr: 'دب قوي وطيب القلب، وفي ومستعد دائماً لمساندة فريقه في الجولات الصعبة.',
    archetype: 'bear',
    placeholderAsset: 'mascot_barood.png',
    isStarter: true,
    isActive: true,
    sortOrder: 13,
  },
  {
    slug: 'fofo-hedgehog',
    nameAr: 'فوفو',
    nameEn: 'Fofo',
    descriptionAr: 'قنفذ صغير خجول وذكي جداً في الحسابات والأرقام بدقة.',
    archetype: 'hedgehog',
    placeholderAsset: 'mascot_fofo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 14,
  },
  {
    slug: 'spark-dragon',
    nameAr: 'سبارك',
    nameEn: 'Spark',
    descriptionAr: 'تنين أسطوري صغير ينفث شرارات الفرح وحماس الفوز.',
    archetype: 'dragon',
    placeholderAsset: 'mascot_spark.png',
    isStarter: true,
    isActive: true,
    sortOrder: 15,
  },
  {
    slug: 'yoyo-sloth',
    nameAr: 'يويو',
    nameEn: 'Yoyo',
    descriptionAr: 'كسلان فيلسوف يأخذ الأمور بروية وتفكير عميق قبل اتخاذ أي قرار.',
    archetype: 'sloth',
    placeholderAsset: 'mascot_yoyo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 16,
  },
  {
    slug: 'blu-whale',
    nameAr: 'بلو',
    nameEn: 'Blu',
    descriptionAr: 'حوت خيالي لطيف يفيض بالطاقة الإيجابية والهدوء الداخلي.',
    archetype: 'whale',
    placeholderAsset: 'mascot_blu.png',
    isStarter: true,
    isActive: true,
    sortOrder: 17,
  },
  {
    slug: 'milo-deer',
    nameAr: 'ميلو',
    nameEn: 'Milo',
    descriptionAr: 'غزال رشيق أنيق يمتلك سرعة بديهة ورد فعل خاطفة.',
    archetype: 'deer',
    placeholderAsset: 'mascot_milo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 18,
  },
  {
    slug: 'oreo-badger',
    nameAr: 'أوريو',
    nameEn: 'Oreo',
    descriptionAr: 'غرير شجاع لا يستسلم ويثابر حتى آخر ثانية في الجولة.',
    archetype: 'badger',
    placeholderAsset: 'mascot_oreo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 19,
  },
  {
    slug: 'starry-spirit',
    nameAr: 'نجم',
    nameEn: 'Najm',
    descriptionAr: 'روح نجمية خيالية مضيئة، تحب السهر والاحتفال بالانتصارات والبطولات.',
    archetype: 'fantasy_star',
    placeholderAsset: 'mascot_starry.png',
    isStarter: true,
    isActive: true,
    sortOrder: 20,
  },
];

export async function seedStarterCompanions() {
  console.log('Seeding 20 O2 Universe starter companions...');
  for (const companion of STARTER_COMPANIONS) {
    await prisma.character.upsert({
      where: { slug: companion.slug },
      update: companion,
      create: companion,
    });
  }
  console.log('Successfully seeded 20 starter companions.');
}

if (typeof require !== 'undefined' && require.main === module) {
  seedStarterCompanions()
    .catch((e) => {
      console.error('Seed error:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
