import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const STARTER_COMPANIONS = [
  {
    slug: 'bando-panda',
    nameAr: 'باندو',
    nameEn: 'Bando',
    descriptionAr: 'الباندا الحكيم الهادئ، محب للمشروبات المنعشة والمجالس الهادئة.',
    archetype: 'panda',
    placeholderAsset: 'mascot_bando.png',
    isStarter: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    slug: 'luna-bunny',
    nameAr: 'لونا',
    nameEn: 'Luna',
    descriptionAr: 'أرنوبة نشيطة سريعة البديهة تعشق المغامرات والتحديات الجماعية.',
    archetype: 'bunny',
    placeholderAsset: 'mascot_luna.png',
    isStarter: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    slug: 'misho-cat',
    nameAr: 'ميشو',
    nameEn: 'Misho',
    descriptionAr: 'قط فضولي ذكي ولعوب، يراقب كل خطوة في اللعبة بحماس.',
    archetype: 'cat',
    placeholderAsset: 'mascot_misho.png',
    isStarter: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    slug: 'zaatar-fox',
    nameAr: 'زعتر',
    nameEn: 'Zaatar',
    descriptionAr: 'ثعلب ذكي ومكار ولطيف، خبير في استراتيجيات ألعاب الورق والخداع.',
    archetype: 'fox',
    placeholderAsset: 'mascot_zaatar.png',
    isStarter: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    slug: 'kiki-koala',
    nameAr: 'كيكي',
    nameEn: 'Kiki',
    descriptionAr: 'كوالا محبوب هادئ الطباع يحب الاسترخاء والمشروبات الساخنة.',
    archetype: 'koala',
    placeholderAsset: 'mascot_kiki.png',
    isStarter: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    slug: 'fando-penguin',
    nameAr: 'فندو',
    nameEn: 'Fando',
    descriptionAr: 'بطريق شهم مرح متزلج، ينشر البهجة والضحك أينما حل.',
    archetype: 'penguin',
    placeholderAsset: 'mascot_fando.png',
    isStarter: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    slug: 'rocco-raccoon',
    nameAr: 'روكو',
    nameEn: 'Rocco',
    descriptionAr: 'راكون مستكشف ذو حيلة وبراعة في حل الألغاز واقتناص الفرص.',
    archetype: 'raccoon',
    placeholderAsset: 'mascot_rocco.png',
    isStarter: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    slug: 'dino-rexy',
    nameAr: 'ركسي',
    nameEn: 'Rexy',
    descriptionAr: 'ديناصور صغير لطيف وشجاع، قلبه كبير ويحب تشجيع أصدقائه.',
    archetype: 'tiny_dino',
    placeholderAsset: 'mascot_rexy.png',
    isStarter: true,
    isActive: true,
    sortOrder: 8,
  },
  {
    slug: 'simba-lion',
    nameAr: 'سيمو',
    nameEn: 'Simo',
    descriptionAr: 'شبل مرح وقائد بالفطرة يحب التنافس الحماسي الشريف.',
    archetype: 'lion_cub',
    placeholderAsset: 'mascot_simo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    slug: 'nimo-otter',
    nameAr: 'نيمو',
    nameEn: 'Nimo',
    descriptionAr: 'قضاعة مائية مرحة وسريعة، محبة للمنافسات السريعة والمرح.',
    archetype: 'otter',
    placeholderAsset: 'mascot_nimo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    slug: 'zizo-monkey',
    nameAr: 'زيزو',
    nameEn: 'Zizo',
    descriptionAr: 'قرد بارع في الحيل والقفز، لا يمل من المزاح وإشعال أجواء التحدي.',
    archetype: 'monkey',
    placeholderAsset: 'mascot_zizo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    slug: 'tut-bird',
    nameAr: 'توت',
    nameEn: 'Tut',
    descriptionAr: 'طائر مغرد متفائل يجلب الحظ السعيد والأخبار الطيبة دائماً.',
    archetype: 'bird',
    placeholderAsset: 'mascot_tut.png',
    isStarter: true,
    isActive: true,
    sortOrder: 12,
  },
  {
    slug: 'barood-bear',
    nameAr: 'بارود',
    nameEn: 'Barood',
    descriptionAr: 'دب قوي وطيب القلب، وفي ومستعد دائماً لمساندة فريقه في الجولات الصعبة.',
    archetype: 'bear',
    placeholderAsset: 'mascot_barood.png',
    isStarter: true,
    isActive: true,
    sortOrder: 13,
  },
  {
    slug: 'fofo-hedgehog',
    nameAr: 'فوفو',
    nameEn: 'Fofo',
    descriptionAr: 'قنفذ صغير خجول وذكي جداً في الحسابات والأرقام بدقة.',
    archetype: 'hedgehog',
    placeholderAsset: 'mascot_fofo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 14,
  },
  {
    slug: 'spark-dragon',
    nameAr: 'سبارك',
    nameEn: 'Spark',
    descriptionAr: 'تنين أسطوري صغير ينفث شرارات الفرح وحماس الفوز.',
    archetype: 'dragon',
    placeholderAsset: 'mascot_spark.png',
    isStarter: true,
    isActive: true,
    sortOrder: 15,
  },
  {
    slug: 'yoyo-sloth',
    nameAr: 'يويو',
    nameEn: 'Yoyo',
    descriptionAr: 'كسلان فيلسوف يأخذ الأمور بروية وتفكير عميق قبل اتخاذ أي قرار.',
    archetype: 'sloth',
    placeholderAsset: 'mascot_yoyo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 16,
  },
  {
    slug: 'blu-whale',
    nameAr: 'بلو',
    nameEn: 'Blu',
    descriptionAr: 'حوت خيالي لطيف يفيض بالطاقة الإيجابية والهدوء الداخلي.',
    archetype: 'whale',
    placeholderAsset: 'mascot_blu.png',
    isStarter: true,
    isActive: true,
    sortOrder: 17,
  },
  {
    slug: 'milo-deer',
    nameAr: 'ميلو',
    nameEn: 'Milo',
    descriptionAr: 'غزال رشيق أنيق يمتلك سرعة بديهة ورد فعل خاطفة.',
    archetype: 'deer',
    placeholderAsset: 'mascot_milo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 18,
  },
  {
    slug: 'oreo-badger',
    nameAr: 'أوريو',
    nameEn: 'Oreo',
    descriptionAr: 'غرير شجاع لا يستسلم ويثابر حتى آخر ثانية في الجولة.',
    archetype: 'badger',
    placeholderAsset: 'mascot_oreo.png',
    isStarter: true,
    isActive: true,
    sortOrder: 19,
  },
  {
    slug: 'starry-spirit',
    nameAr: 'نجم',
    nameEn: 'Najm',
    descriptionAr: 'روح نجمية خيالية مضيئة، تحب السهر والاحتفال بالانتصارات والبطولات.',
    archetype: 'fantasy_star',
    placeholderAsset: 'mascot_starry.png',
    isStarter: true,
    isActive: true,
    sortOrder: 20,
  },
];

export const PHASE4_ITEM_DEFINITIONS = [
  // Consumables
  {
    slug: 'shawarma_mini',
    type: 'CONSUMABLE' as const,
    rarity: 'COMMON' as const,
    nameAr: 'شاورما O2 ميني',
    nameEn: 'O2 Mini Shawarma',
    descriptionAr: 'وجبة خفيفة شهية تمنح رفيقك شبعاً وسعادة فورية.',
    descriptionEn: 'A tasty classic snack giving hunger and mood boost.',
    assetKey: 'food_shawarma_mini',
    cosmeticSlot: null,
    hungerDelta: 30.0,
    cleanlinessDelta: 0.0,
    energyDelta: 5.0,
    moodDelta: 10.0,
    reactionKey: 'YUMMY_SHAWARMA',
    isActive: true,
    isStackable: true,
    sortOrder: 1,
    offer: {
      slug: 'offer_shawarma_mini',
      priceAmount: BigInt(40),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'pizza_cheesy',
    type: 'CONSUMABLE' as const,
    rarity: 'UNCOMMON' as const,
    nameAr: 'شريحة بيتزا O2 بالجبن',
    nameEn: 'O2 Cheesy Pizza Slice',
    descriptionAr: 'شريحة ساخنة محشوة بالجبن تعيد الحيوية والبهجة.',
    descriptionEn: 'Fresh hot pizza slice full of melted cheese goodness.',
    assetKey: 'food_pizza_cheesy',
    cosmeticSlot: null,
    hungerDelta: 45.0,
    cleanlinessDelta: -5.0,
    energyDelta: 10.0,
    moodDelta: 15.0,
    reactionKey: 'CHEESY_DELIGHT',
    isActive: true,
    isStackable: true,
    sortOrder: 2,
    offer: {
      slug: 'offer_pizza_cheesy',
      priceAmount: BigInt(60),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'crispy_fries',
    type: 'CONSUMABLE' as const,
    rarity: 'COMMON' as const,
    nameAr: 'بطاطس O2 المقرمشة',
    nameEn: 'O2 Crispy Fries',
    descriptionAr: 'بطاطس مقلية ذهبية خفيفة ومسلية أثناء الجولات.',
    descriptionEn: 'Golden crispy fries perfect for quick snack.',
    assetKey: 'food_crispy_fries',
    cosmeticSlot: null,
    hungerDelta: 20.0,
    cleanlinessDelta: 0.0,
    energyDelta: 5.0,
    moodDelta: 10.0,
    reactionKey: 'CRUNCHY_JOY',
    isActive: true,
    isStackable: true,
    sortOrder: 3,
    offer: {
      slug: 'offer_crispy_fries',
      priceAmount: BigInt(30),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'craft_burger',
    type: 'CONSUMABLE' as const,
    rarity: 'RARE' as const,
    nameAr: 'برجر O2 كرافت الفاخر',
    nameEn: 'O2 Craft Burger',
    descriptionAr: 'برجر مشوي ممتاز يشبع رفيقك بالكامل ويرفع معنوياته لأعلى المستويات.',
    descriptionEn: 'Premium grilled burger for full hunger restoration.',
    assetKey: 'food_craft_burger',
    cosmeticSlot: null,
    hungerDelta: 60.0,
    cleanlinessDelta: -5.0,
    energyDelta: 15.0,
    moodDelta: 25.0,
    reactionKey: 'BURGER_FEST',
    isActive: true,
    isStackable: true,
    sortOrder: 4,
    offer: {
      slug: 'offer_craft_burger',
      priceAmount: BigInt(75),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'gelato_cup',
    type: 'CONSUMABLE' as const,
    rarity: 'UNCOMMON' as const,
    nameAr: 'كوب جيلاتو O2 المنعش',
    nameEn: 'O2 Gelato Cup',
    descriptionAr: 'حلوى إيطالية منعشة تبهج الرفيق وتمنحه نشاطاً مرحاً.',
    descriptionEn: 'Refreshing creamy dessert bringing pure companion joy.',
    assetKey: 'food_gelato_cup',
    cosmeticSlot: null,
    hungerDelta: 25.0,
    cleanlinessDelta: 0.0,
    energyDelta: 10.0,
    moodDelta: 35.0,
    reactionKey: 'SWEET_HAPPINESS',
    isActive: true,
    isStackable: true,
    sortOrder: 5,
    offer: {
      slug: 'offer_gelato_cup',
      priceAmount: BigInt(50),
      currencyKind: 'COIN' as const,
    },
  },

  // Cosmetics
  {
    slug: 'cap_classic_o2',
    type: 'COSMETIC' as const,
    rarity: 'COMMON' as const,
    nameAr: 'قبعة O2 الكلاسيكية',
    nameEn: 'O2 Classic Cap',
    descriptionAr: 'قبعة حمراء أنيقة تحمل شعار O2 المميز.',
    descriptionEn: 'Iconic red cap with embroidered O2 emblem.',
    assetKey: 'cosmetic_cap_classic',
    cosmeticSlot: 'HEAD' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 6,
    offer: {
      slug: 'offer_cap_classic_o2',
      priceAmount: BigInt(100),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'glasses_retro_shades',
    type: 'COSMETIC' as const,
    rarity: 'UNCOMMON' as const,
    nameAr: 'نظارات ريترو أنيقة',
    nameEn: 'Retro Shades',
    descriptionAr: 'نظارات شمسية عصرية لإطلالة واثقة وجذابة.',
    descriptionEn: 'Stylish dark sunglasses for a cool companion look.',
    assetKey: 'cosmetic_glasses_retro',
    cosmeticSlot: 'FACE' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 7,
    offer: {
      slug: 'offer_glasses_retro_shades',
      priceAmount: BigInt(150),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'headphones_neon_beats',
    type: 'COSMETIC' as const,
    rarity: 'RARE' as const,
    nameAr: 'سماعات نيون بيتس',
    nameEn: 'Neon Beats Headphones',
    descriptionAr: 'سماعات رأس مضيئة للموسيقى الحماسية داخل اللوبي.',
    descriptionEn: 'Glowing neon DJ headphones for vibrant music lovers.',
    assetKey: 'cosmetic_headphones_neon',
    cosmeticSlot: 'HEAD' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 8,
    offer: {
      slug: 'offer_headphones_neon_beats',
      priceAmount: BigInt(250),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'backpack_nomad',
    type: 'COSMETIC' as const,
    rarity: 'RARE' as const,
    nameAr: 'حقيبة الرحالة المستكشف',
    nameEn: 'Nomad Explorer Backpack',
    descriptionAr: 'حقيبة ظهر متينة للمغامرين ومحبي جمع المقتنيات.',
    descriptionEn: 'Sturdy travel backpack for adventurous companions.',
    assetKey: 'cosmetic_backpack_nomad',
    cosmeticSlot: 'BACK' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 9,
    offer: {
      slug: 'offer_backpack_nomad',
      priceAmount: BigInt(300),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'aura_golden_sparkle',
    type: 'COSMETIC' as const,
    rarity: 'EPIC' as const,
    nameAr: 'هالة البريق الذهبي',
    nameEn: 'Golden Sparkle Aura',
    descriptionAr: 'هالة ذهبية متلألئة تحيط بالرفيق وتجذب الأنظار.',
    descriptionEn: 'Glimmering gold particle aura surrounding companion.',
    assetKey: 'cosmetic_aura_golden',
    cosmeticSlot: 'AURA' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 10,
    offer: {
      slug: 'offer_aura_golden_sparkle',
      priceAmount: BigInt(500),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'frame_champion_gold',
    type: 'COSMETIC' as const,
    rarity: 'EPIC' as const,
    nameAr: 'إطار بطل O2 الذهبي',
    nameEn: 'O2 Champion Gold Frame',
    descriptionAr: 'إطار بطولات ذهبي فخم يزين الملف الشخصي.',
    descriptionEn: 'Prestigious golden championship frame for profile display.',
    assetKey: 'cosmetic_frame_champion',
    cosmeticSlot: 'NAME_FRAME' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 11,
    offer: {
      slug: 'offer_frame_champion_gold',
      priceAmount: BigInt(500),
      currencyKind: 'COIN' as const,
    },
  },
  {
    slug: 'outfit_cyber_hoodie',
    type: 'COSMETIC' as const,
    rarity: 'LEGENDARY' as const,
    nameAr: 'هودي سايبر المستقبلي',
    nameEn: 'Cyber Future Hoodie',
    descriptionAr: 'زي أسطوري استثنائي يعكس هوية عالم O2 الرقمي المتطور.',
    descriptionEn: 'Legendary cyber hoodie crafted for stylish companions.',
    assetKey: 'cosmetic_outfit_cyber',
    cosmeticSlot: 'BODY' as const,
    hungerDelta: null,
    cleanlinessDelta: null,
    energyDelta: null,
    moodDelta: null,
    reactionKey: null,
    isActive: true,
    isStackable: false,
    sortOrder: 12,
    offer: {
      slug: 'offer_outfit_cyber_hoodie',
      priceAmount: BigInt(50),
      currencyKind: 'GEM' as const,
    },
  },
];

export async function seedStarterCompanions() {
  console.log('Seeding 20 O2 Universe starter companions...');
  for (const companion of STARTER_COMPANIONS) {
    await prisma.character.upsert({
      where: { slug: companion.slug },
      update: companion,
      create: companion,
    });
  }
  console.log('Successfully seeded 20 starter companions.');
}

export async function seedPhase4Catalog() {
  console.log('Seeding Phase 4 Item Catalog and Shop Offers...');
  for (const item of PHASE4_ITEM_DEFINITIONS) {
    const { offer, ...itemData } = item;
    const createdItem = await prisma.itemDefinition.upsert({
      where: { slug: item.slug },
      update: itemData,
      create: itemData,
    });

    if (item.type === 'COSMETIC') {
      const characters = await prisma.character.findMany({ select: { id: true } });
      for (const character of characters) {
        await prisma.cosmeticVariant.upsert({
          where: { itemId_characterId: { itemId: createdItem.id, characterId: character.id } },
          update: { assetKey: item.assetKey },
          create: { itemId: createdItem.id, characterId: character.id, assetKey: item.assetKey },
        });
      }
    }

    if (offer) {
      await prisma.shopOffer.upsert({
        where: { slug: offer.slug },
        update: {
          itemId: createdItem.id,
          itemQuantity: 1,
          currencyKind: offer.currencyKind,
          priceAmount: offer.priceAmount,
          isActive: true,
          sortOrder: item.sortOrder,
        },
        create: {
          slug: offer.slug,
          itemId: createdItem.id,
          itemQuantity: 1,
          currencyKind: offer.currencyKind,
          priceAmount: offer.priceAmount,
          isActive: true,
          sortOrder: item.sortOrder,
        },
      });
    }
  }
  console.log(`Successfully seeded ${PHASE4_ITEM_DEFINITIONS.length} item definitions and offers.`);
}

export async function main() {
  await seedStarterCompanions();
  await seedPhase4Catalog();
}

if (typeof require !== 'undefined' && require.main === module) {
  main()
    .catch((e) => {
      console.error('Seed error:', e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
