export const SOCIAL_LIMITS = {
  SEARCH_PER_MINUTE: 30,
  FRIEND_REQUESTS_PER_MINUTE: 10,
  PARTY_INVITES_PER_MINUTE: 20,
  PARTY_CODE_ATTEMPTS_PER_MINUTE: 20,
  BLOCK_ACTIONS_PER_MINUTE: 20,
  PAGE_SIZE_MAX: 50,
  SEARCH_RESULTS_MAX: 10,
  SEARCH_MIN_LENGTH: 3,
} as const;

export const SocialErrorCodes = {
  INVALID_TARGET: 'INVALID_TARGET',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  FRIEND_REQUESTS_DISABLED: 'FRIEND_REQUESTS_DISABLED',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  SOCIAL_ACTION_UNAVAILABLE: 'SOCIAL_ACTION_UNAVAILABLE',
  NOT_FRIENDS: 'NOT_FRIENDS',
  PARTY_NOT_FOUND: 'PARTY_NOT_FOUND',
  PARTY_FULL: 'PARTY_FULL',
  ALREADY_IN_PARTY: 'ALREADY_IN_PARTY',
  NOT_PARTY_LEADER: 'NOT_PARTY_LEADER',
  PARTY_INVITE_NOT_FOUND: 'PARTY_INVITE_NOT_FOUND',
  PARTY_INVITE_EXPIRED: 'PARTY_INVITE_EXPIRED',
  PARTY_GAME_CAPACITY_EXCEEDED: 'PARTY_GAME_CAPACITY_EXCEEDED',
  PARTY_CODE_DISABLED: 'PARTY_CODE_DISABLED',
} as const;
