export const EconomyErrorCodes = {
  ECONOMY_NOT_INITIALIZED: 'ECONOMY_NOT_INITIALIZED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  INVALID_CURRENCY_SCOPE: 'INVALID_CURRENCY_SCOPE',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  OFFER_NOT_FOUND: 'OFFER_NOT_FOUND',
  OFFER_INACTIVE: 'OFFER_INACTIVE',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_INACTIVE: 'ITEM_INACTIVE',
  ITEM_NOT_OWNED: 'ITEM_NOT_OWNED',
  ITEM_NOT_CONSUMABLE: 'ITEM_NOT_CONSUMABLE',
  ITEM_NOT_AVAILABLE: 'ITEM_NOT_AVAILABLE',
  ITEM_ALREADY_OWNED: 'ITEM_ALREADY_OWNED',
  COSMETIC_NOT_OWNED: 'COSMETIC_NOT_OWNED',
  COSMETIC_INCOMPATIBLE: 'COSMETIC_INCOMPATIBLE',
  INVALID_COSMETIC_SLOT: 'INVALID_COSMETIC_SLOT',
  IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST: 'IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST',
  PURCHASE_ALREADY_COMPLETED: 'PURCHASE_ALREADY_COMPLETED',
} as const;

export type EconomyErrorCode = keyof typeof EconomyErrorCodes;
